
version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - docker login -u $dockerhub_username -p $dockerhub_password
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --registry-ids 106260173616 --region ap-northeast-1)
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - echo Building the Docker image...
      - sh build.sh
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 106260173616.dkr.ecr.ap-northeast-1.amazonaws.com/aws_final_project:latest
artifacts:
  files:
  - cicdtest-0.0.1-SNAPSHOT.jar
  - appspec.yml
  discard-paths: yes
